// COLOR CONSTANTS
export const COLORS = {
    NEON_GREEN: '#32CD32',
    BALANCED_GREEN: '#4CAF50',
    DARK_GRAY: '#1E1E1E',
    BLACK: '#121212',
    MEDIUM_GRAY: '#2A2A2A',
    LIGHT_GRAY: '#B0B0B0',
    WHITE: '#F5F5F5'
  };

export default COLORS